version: 2
defaultBuild: &defaultBuild
  working_directory: ~/workspace
  docker:
    - image: cainchen/circleci-ubuntu14.04-ansible
jobs:
  test-1:
    <<: *defaultBuild
    steps:
      - run:
          name: Test 1 
          command: |
            curl --version
  test-2:
    <<: *defaultBuild
    steps:
      - run:
          name: Test 2
          command: |
            hostname

workflows:
  version: 2
  TEST-workflows:
    jobs:
      - test-1
      - test-2
